### ISSUE TITLE
Getting an error when running mlagents-learn --help

### ISSUE THREAD

**Issue by HasarinduPerera** [CoderOneHQ/ultimate-volleyball#9]
Hi, I am trying to setup ML-Agents Python package but getting this error. I see it says `Downgrade the protobuf package to 3.20.x or lower.`  but I am kind of confused and hoping for some guidance.

```Traceback (most recent call last):
  File "/media/user/Unity/Projects/.default-env/bin/mlagents-learn", line 5, in <module>
    from mlagents.trainers.learn import main
  File "/media/user/Unity/Projects/.default-env/lib/python3.8/site-packages/mlagents/trainers/learn.py", line 2, in <module>
    from mlagents import torch_utils
  File "/media/user/Unity/Projects/.default-env/lib/python3.8/site-packages/mlagents/torch_utils/__init__.py", line 1, in <module>
    from mlagents.torch_utils.torch import torch as torch  # noqa
  File "/media/user/Unity/Projects/.default-env/lib/python3.8/site-packages/mlagents/torch_utils/torch.py", line 6, in <module>
    from mlagents.trainers.settings import TorchSettings
  File "/media/user/Unity/Projects/.default-env/lib/python3.8/site-packages/mlagents/trainers/settings.py", line 25, in <module>
    from mlagents.trainers.cli_utils import StoreConfigFile, DetectDefault, parser
  File "/media/user/Unity/Projects/.default-env/lib/python3.8/site-packages/mlagents/trainers/cli_utils.py", line 5, in <module>
    from mlagents_envs.environment import UnityEnvironment
  File "/media/user/Unity/Projects/.default-env/lib/python3.8/site-packages/mlagents_envs/environment.py", line 12, in <module>
    from mlagents_envs.side_channel.side_channel import SideChannel
  File "/media/user/Unity/Projects/.default-env/lib/python3.8/site-packages/mlagents_envs/side_channel/__init__.py", line 5, in <module>
    from mlagents_envs.side_channel.default_training_analytics_side_channel import (  # noqa
  File "/media/user/Unity/Projects/.default-env/lib/python3.8/site-packages/mlagents_envs/side_channel/default_training_analytics_side_channel.py", line 7, in <module>
    from mlagents_envs.communicator_objects.training_analytics_pb2 import (
  File "/media/user/Unity/Projects/.default-env/lib/python3.8/site-packages/mlagents_envs/communicator_objects/training_analytics_pb2.py", line 35, in <module>
    _descriptor.FieldDescriptor(
  File "/media/user/Unity/Projects/.default-env/lib/python3.8/site-packages/google/protobuf/descriptor.py", line 560, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates```

**Comment by joooyzee** [comment]
Can you try `pip3 install --upgrade protobuf==3.20.0` and see if that fixes the issue?

**Comment by HasarinduPerera** [comment]
It does, thank you!
